[projects."/home/namalkanti"]
trust_level = "untrusted"

[projects."/home/namalkanti/Drive/Stuffz/Programming/Rust/ExtremeMenuNavigation"]
trust_level = "untrusted"

[projects."/home/namalkanti/.codex"]
trust_level = "untrusted"

[projects."/home/namalkanti/.config/dotfiles"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"
